// <auto-generated/>
using System;
using System.Collections.Generic;

namespace Pine.uGUI
{
    public static partial class P
    {
        /// <summary>Returns the API version.</summary>
        public static Version Version
        {
            get => global::Pine.Core.Version;
        }

        /// <summary>Global explicit reactive motion preference.</summary>
        public static Source<bool> ReducedMotion
        {
            get => global::Pine.Core.ReducedMotion;
        }

        /// <summary>Controls duplicate named-property diagnostics within groups and duplicate child transform diagnostics.</summary>
        public static bool Strict
        {
            get => global::Pine.Core.Strict;
            set => global::Pine.Core.Strict = value;
        }

        /// <summary>Controls required native wiring for the imperative Create API.</summary>
        public static bool Defaults
        {
            get => global::Pine.Core.Defaults;
            set => global::Pine.Core.Defaults = value;
        }

        /// <summary>Controls whether nested groups are traversed after outer declarations within property ordering phases.</summary>
        public static bool DeferNestedProperties
        {
            get => global::Pine.Core.DeferNestedProperties;
            set => global::Pine.Core.DeferNestedProperties = value;
        }

        /// <summary>Creates mutable typed state, usable outside any ownership scope.</summary>
        public static Source<T> Source<T>(
            T value = default,
            IEqualityComparer<T> comparer = null
        ) => global::Pine.Core.Source<T>(value, comparer);

        /// <summary>Adapts a tracked calculation to a typed declaration input.</summary>
        public static Value<T> Value<T>(Func<T> read) => global::Pine.Core.Value<T>(read);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Value<T> value) => global::Pine.Core.Read<T>(value);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Func<T> getter) => global::Pine.Core.Read<T>(getter);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Source<T> source) => global::Pine.Core.Read<T>(source);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(ReadOnly<T> source) => global::Pine.Core.Read<T>(source);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Derived<T> derived) => global::Pine.Core.Read<T>(derived);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(T value) => global::Pine.Core.Read<T>(value);

        /// <summary>Creates an owned eager cached calculation.</summary>
        public static Derived<T> Derive<T>(Func<T> compute, IEqualityComparer<T> comparer = null) =>
            global::Pine.Core.Derive<T>(compute, comparer);

        /// <summary>Runs an owned side effect immediately and again after its tracked inputs change.</summary>
        public static IDisposable Effect(Action action) => global::Pine.Core.Effect(action);

        /// <summary>Runs an owned side effect immediately and again after its tracked inputs change.</summary>
        public static IDisposable Effect<T>(Func<T, T> action, T initial) =>
            global::Pine.Core.Effect<T>(action, initial);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static Scope Root(Action build) => global::Pine.Core.Root(build);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static Scope Root(Action<Action> build) => global::Pine.Core.Root(build);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static (Scope Scope, T Value) Root<T>(Func<Action, T> build) =>
            global::Pine.Core.Root<T>(build);

        internal static Scope OwnedRoot(Action build) => global::Pine.Core.OwnedRoot(build);

        /// <summary>A scoped typed dependency with a fallback outside providers.</summary>
        public static Context<T> Context<T>(T fallback = default) =>
            global::Pine.Core.Context<T>(fallback);

        /// <summary>Registers a callback, disposable or Unity object with the active scope.</summary>
        public static void Cleanup(Action cleanup) => global::Pine.Core.Cleanup(cleanup);

        /// <summary>Registers a callback, disposable or Unity object with the active scope.</summary>
        public static void Cleanup(IDisposable disposable) => global::Pine.Core.Cleanup(disposable);

        /// <summary>Runs several writes as one synchronous update transaction.</summary>
        public static void Batch(Action action) => global::Pine.Core.Batch(action);

        /// <summary>Runs a read or action with dependency collection temporarily suspended.</summary>
        public static T Untrack<T>(Func<T> read) => global::Pine.Core.Untrack<T>(read);

        /// <summary>Runs a read or action with dependency collection temporarily suspended.</summary>
        public static void Untrack(Action action) => global::Pine.Core.Untrack(action);

        /// <summary>Advances the shared spring/polling/exit-delay clock manually by a finite non-negative number of seconds.</summary>
        public static void Step(double deltaTime) => global::Pine.Core.Step(deltaTime);

        internal static Scope RequireScope() => global::Pine.Core.RequireScope();

        internal static void RequireStable() => global::Pine.Core.RequireStable();

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<TResult>(
            Func<bool> condition,
            Func<TResult> build,
            Func<TResult> fallback = null
        ) => global::Pine.Core.Show<TResult>(condition, build, fallback);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            Func<TKey, TResult> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, build, comparer);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<int, ReadOnly<TValue>, TResult> build
        ) => global::Pine.Core.Indexes<TValue, TResult>(read, build);

        /// <summary>Retains rows by value identity and exposes each current index as a read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Values<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<TValue, ReadOnly<int>, TResult> build,
            IEqualityComparer<TValue> comparer = null
        ) => global::Pine.Core.Values<TValue, TResult>(read, build, comparer);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            Func<TKey, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, build, comparer);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            IReadOnlyDictionary<TKey, Func<ReadOnly<bool>, Branch<TResult>>> branches,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, branches, fallback);

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<TResult>(
            Func<bool> condition,
            Func<ReadOnly<bool>, Branch<TResult>> build,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Show<TResult>(condition, build, fallback);

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<T, TResult>(
            Func<T> read,
            Predicate<T> truthy,
            Func<ReadOnly<T>, ReadOnly<bool>, Branch<TResult>> build,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Show<T, TResult>(read, truthy, build, fallback);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TKey, TValue, TResult>(
            Func<IEnumerable<KeyValuePair<TKey, TValue>>> read,
            Func<TKey, ReadOnly<TValue>, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Indexes<TKey, TValue, TResult>(read, build, comparer);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<int, ReadOnly<TValue>, ReadOnly<bool>, Branch<TResult>> build
        ) => global::Pine.Core.Indexes<TValue, TResult>(read, build);

        /// <summary>Retains rows by value identity and exposes each current index as a read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Values<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<TValue, ReadOnly<int>, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TValue> comparer = null
        ) => global::Pine.Core.Values<TValue, TResult>(read, build, comparer);

        /// <summary>An owned reactive analytic spring whose output moves toward a tracked target.</summary>
        public static Spring<T> Spring<T>(
            Func<T> target,
            Value<double>? period = null,
            Value<double>? dampingRatio = null,
            SpringSpace<T> space = null
        ) => global::Pine.Core.Spring<T>(target, period, dampingRatio, space);

        /// <summary>Creates a typed native reference for forward, cyclic and conditional links.</summary>
        public static Ref<T> Ref<T>()
            where T : class => global::Pine.Core.Ref<T>();
    }
}

namespace Pine.UIToolkit
{
    public static partial class P
    {
        /// <summary>Returns the API version.</summary>
        public static Version Version
        {
            get => global::Pine.Core.Version;
        }

        /// <summary>Global explicit reactive motion preference.</summary>
        public static Source<bool> ReducedMotion
        {
            get => global::Pine.Core.ReducedMotion;
        }

        /// <summary>Controls duplicate named-property diagnostics within groups and duplicate child transform diagnostics.</summary>
        public static bool Strict
        {
            get => global::Pine.Core.Strict;
            set => global::Pine.Core.Strict = value;
        }

        /// <summary>Controls required native wiring for the imperative Create API.</summary>
        public static bool Defaults
        {
            get => global::Pine.Core.Defaults;
            set => global::Pine.Core.Defaults = value;
        }

        /// <summary>Controls whether nested groups are traversed after outer declarations within property ordering phases.</summary>
        public static bool DeferNestedProperties
        {
            get => global::Pine.Core.DeferNestedProperties;
            set => global::Pine.Core.DeferNestedProperties = value;
        }

        /// <summary>Creates mutable typed state, usable outside any ownership scope.</summary>
        public static Source<T> Source<T>(
            T value = default,
            IEqualityComparer<T> comparer = null
        ) => global::Pine.Core.Source<T>(value, comparer);

        /// <summary>Adapts a tracked calculation to a typed declaration input.</summary>
        public static Value<T> Value<T>(Func<T> read) => global::Pine.Core.Value<T>(read);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Value<T> value) => global::Pine.Core.Read<T>(value);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Func<T> getter) => global::Pine.Core.Read<T>(getter);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Source<T> source) => global::Pine.Core.Read<T>(source);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(ReadOnly<T> source) => global::Pine.Core.Read<T>(source);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(Derived<T> derived) => global::Pine.Core.Read<T>(derived);

        /// <summary>Reads a typed literal or reactive adapter.</summary>
        public static T Read<T>(T value) => global::Pine.Core.Read<T>(value);

        /// <summary>Creates an owned eager cached calculation.</summary>
        public static Derived<T> Derive<T>(Func<T> compute, IEqualityComparer<T> comparer = null) =>
            global::Pine.Core.Derive<T>(compute, comparer);

        /// <summary>Runs an owned side effect immediately and again after its tracked inputs change.</summary>
        public static IDisposable Effect(Action action) => global::Pine.Core.Effect(action);

        /// <summary>Runs an owned side effect immediately and again after its tracked inputs change.</summary>
        public static IDisposable Effect<T>(Func<T, T> action, T initial) =>
            global::Pine.Core.Effect<T>(action, initial);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static Scope Root(Action build) => global::Pine.Core.Root(build);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static Scope Root(Action<Action> build) => global::Pine.Core.Root(build);

        /// <summary>Constructs an independent ownership scope and runs its builder without dependency tracking.</summary>
        public static (Scope Scope, T Value) Root<T>(Func<Action, T> build) =>
            global::Pine.Core.Root<T>(build);

        internal static Scope OwnedRoot(Action build) => global::Pine.Core.OwnedRoot(build);

        /// <summary>A scoped typed dependency with a fallback outside providers.</summary>
        public static Context<T> Context<T>(T fallback = default) =>
            global::Pine.Core.Context<T>(fallback);

        /// <summary>Registers a callback, disposable or Unity object with the active scope.</summary>
        public static void Cleanup(Action cleanup) => global::Pine.Core.Cleanup(cleanup);

        /// <summary>Registers a callback, disposable or Unity object with the active scope.</summary>
        public static void Cleanup(IDisposable disposable) => global::Pine.Core.Cleanup(disposable);

        /// <summary>Runs several writes as one synchronous update transaction.</summary>
        public static void Batch(Action action) => global::Pine.Core.Batch(action);

        /// <summary>Runs a read or action with dependency collection temporarily suspended.</summary>
        public static T Untrack<T>(Func<T> read) => global::Pine.Core.Untrack<T>(read);

        /// <summary>Runs a read or action with dependency collection temporarily suspended.</summary>
        public static void Untrack(Action action) => global::Pine.Core.Untrack(action);

        /// <summary>Advances the shared spring/polling/exit-delay clock manually by a finite non-negative number of seconds.</summary>
        public static void Step(double deltaTime) => global::Pine.Core.Step(deltaTime);

        internal static Scope RequireScope() => global::Pine.Core.RequireScope();

        internal static void RequireStable() => global::Pine.Core.RequireStable();

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<TResult>(
            Func<bool> condition,
            Func<TResult> build,
            Func<TResult> fallback = null
        ) => global::Pine.Core.Show<TResult>(condition, build, fallback);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            Func<TKey, TResult> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, build, comparer);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<int, ReadOnly<TValue>, TResult> build
        ) => global::Pine.Core.Indexes<TValue, TResult>(read, build);

        /// <summary>Retains rows by value identity and exposes each current index as a read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Values<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<TValue, ReadOnly<int>, TResult> build,
            IEqualityComparer<TValue> comparer = null
        ) => global::Pine.Core.Values<TValue, TResult>(read, build, comparer);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            Func<TKey, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, build, comparer);

        /// <summary>Retains the selected keyed branch and optionally its exiting predecessor.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Switch<TKey, TResult>(
            Func<TKey> select,
            IReadOnlyDictionary<TKey, Func<ReadOnly<bool>, Branch<TResult>>> branches,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Switch<TKey, TResult>(select, branches, fallback);

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<TResult>(
            Func<bool> condition,
            Func<ReadOnly<bool>, Branch<TResult>> build,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Show<TResult>(condition, build, fallback);

        /// <summary>Constructs an owned conditional branch while its condition is true, with an optional fallback.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Show<T, TResult>(
            Func<T> read,
            Predicate<T> truthy,
            Func<ReadOnly<T>, ReadOnly<bool>, Branch<TResult>> build,
            Func<ReadOnly<bool>, Branch<TResult>> fallback = null
        ) => global::Pine.Core.Show<T, TResult>(read, truthy, build, fallback);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TKey, TValue, TResult>(
            Func<IEnumerable<KeyValuePair<TKey, TValue>>> read,
            Func<TKey, ReadOnly<TValue>, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TKey> comparer = null
        ) => global::Pine.Core.Indexes<TKey, TValue, TResult>(read, build, comparer);

        /// <summary>Retains rows by index or explicit dictionary key, updating each row's read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Indexes<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<int, ReadOnly<TValue>, ReadOnly<bool>, Branch<TResult>> build
        ) => global::Pine.Core.Indexes<TValue, TResult>(read, build);

        /// <summary>Retains rows by value identity and exposes each current index as a read-only reactive value.</summary>
        public static ReadOnly<IReadOnlyList<TResult>> Values<TValue, TResult>(
            Func<IReadOnlyList<TValue>> read,
            Func<TValue, ReadOnly<int>, ReadOnly<bool>, Branch<TResult>> build,
            IEqualityComparer<TValue> comparer = null
        ) => global::Pine.Core.Values<TValue, TResult>(read, build, comparer);

        /// <summary>An owned reactive analytic spring whose output moves toward a tracked target.</summary>
        public static Spring<T> Spring<T>(
            Func<T> target,
            Value<double>? period = null,
            Value<double>? dampingRatio = null,
            SpringSpace<T> space = null
        ) => global::Pine.Core.Spring<T>(target, period, dampingRatio, space);

        /// <summary>Creates a typed native reference for forward, cyclic and conditional links.</summary>
        public static Ref<T> Ref<T>()
            where T : class => global::Pine.Core.Ref<T>();
    }
}
