// <auto-generated/>
using System;
using System.Collections.Generic;
using Pine;
using Core = Pine.Core;

namespace Pine.UIToolkit
{
    public static partial class P
    {
        public static Action<global::UnityEngine.UIElements.ITextEdition> TextEdition(
            global::Pine.Value<bool>? @autoCorrection = null,
            global::Pine.Value<bool>? @hideMobileInput = null,
            global::Pine.Value<bool>? @hidePlaceholderOnFocus = null,
            global::Pine.Value<bool>? @isDelayed = null,
            global::Pine.Value<bool>? @isPassword = null,
            global::Pine.Value<bool>? @isReadOnly = null,
            global::Pine.Value<global::UnityEngine.TouchScreenKeyboardType>? @keyboardType = null,
            global::Pine.Value<char>? @maskChar = null,
            global::Pine.Value<int>? @maxLength = null,
            global::Pine.Value<string>? @placeholder = null
#if PINE_UNITY_6000_3_25_OR_NEWER
            ,
            global::Pine.Value<bool>? @hideSoftKeyboard = null
#endif
        ) =>
            native =>
            {
                var node =
                    global::Pine.UIToolkit.Node.Current ?? new Node(null, Core.RequireScope());
                Prop(native, node, "isReadOnly", @isReadOnly, (item, v) => item.@isReadOnly = v);
                Prop(native, node, "maxLength", @maxLength, (item, v) => item.@maxLength = v);
                Prop(native, node, "placeholder", @placeholder, (item, v) => item.@placeholder = v);
                Prop(native, node, "isDelayed", @isDelayed, (item, v) => item.@isDelayed = v);
                Prop(native, node, "maskChar", @maskChar, (item, v) => item.@maskChar = v);
                Prop(native, node, "isPassword", @isPassword, (item, v) => item.@isPassword = v);
                Prop(
                    native,
                    node,
                    "hidePlaceholderOnFocus",
                    @hidePlaceholderOnFocus,
                    (item, v) => item.@hidePlaceholderOnFocus = v
                );
                Prop(
                    native,
                    node,
                    "autoCorrection",
                    @autoCorrection,
                    (item, v) => item.@autoCorrection = v
                );
                Prop(
                    native,
                    node,
                    "hideMobileInput",
                    @hideMobileInput,
                    (item, v) => item.@hideMobileInput = v
                );
                Prop(
                    native,
                    node,
                    "keyboardType",
                    @keyboardType,
                    (item, v) => item.@keyboardType = v
                );
#if PINE_UNITY_6000_3_25_OR_NEWER
                Prop(
                    native,
                    node,
                    "hideSoftKeyboard",
                    @hideSoftKeyboard,
                    (item, v) => item.@hideSoftKeyboard = v
                );
#endif
            };

        public static Action<global::UnityEngine.UIElements.ITextSelection> TextSelection(
            global::Pine.Value<int>? @cursorIndex = null,
            global::Pine.Value<bool>? @doubleClickSelectsWord = null,
            global::Pine.Value<bool>? @isSelectable = null,
            global::Pine.Value<bool>? @selectAllOnFocus = null,
            global::Pine.Value<bool>? @selectAllOnMouseUp = null,
            global::Pine.Value<int>? @selectIndex = null,
            global::Pine.Value<bool>? @tripleClickSelectsLine = null,
            global::System.Action @onCursorIndexChange = null,
            global::System.Action @onSelectIndexChange = null
        ) =>
            native =>
            {
                var node =
                    global::Pine.UIToolkit.Node.Current ?? new Node(null, Core.RequireScope());
                Prop(
                    native,
                    node,
                    "isSelectable",
                    @isSelectable,
                    (item, v) => item.@isSelectable = v
                );
                Prop(native, node, "cursorIndex", @cursorIndex, (item, v) => item.@cursorIndex = v);
                Prop(
                    native,
                    node,
                    "doubleClickSelectsWord",
                    @doubleClickSelectsWord,
                    (item, v) => item.@doubleClickSelectsWord = v
                );
                Prop(native, node, "selectIndex", @selectIndex, (item, v) => item.@selectIndex = v);
                Prop(
                    native,
                    node,
                    "tripleClickSelectsLine",
                    @tripleClickSelectsLine,
                    (item, v) => item.@tripleClickSelectsLine = v
                );
                Prop(
                    native,
                    node,
                    "selectAllOnFocus",
                    @selectAllOnFocus,
                    (item, v) => item.@selectAllOnFocus = v
                );
                Prop(
                    native,
                    node,
                    "selectAllOnMouseUp",
                    @selectAllOnMouseUp,
                    (item, v) => item.@selectAllOnMouseUp = v
                );
                if (@onCursorIndexChange != null)
                    Listen(
                        node,
                        (global::System.Action)(() => Scoped(node, () => @onCursorIndexChange())),
                        handler => native.@OnCursorIndexChange += handler,
                        handler => native.@OnCursorIndexChange -= handler
                    );
                if (@onSelectIndexChange != null)
                    Listen(
                        node,
                        (global::System.Action)(() => Scoped(node, () => @onSelectIndexChange())),
                        handler => native.@OnSelectIndexChange += handler,
                        handler => native.@OnSelectIndexChange -= handler
                    );
            };

        public static Action<global::UnityEngine.UIElements.PanelSettings> PanelSettings(
            global::Pine.Value<global::UnityEngine.UIElements.BindingLogLevel>? @bindingLogLevel =
                null,
            global::Pine.Value<bool>? @clearColor = null,
            global::Pine.Value<bool>? @clearDepthStencil = null,
            ColorValue? @colorClearValue = null,
            global::Pine.Value<global::UnityEngine.UIElements.DynamicAtlasSettings>? @dynamicAtlasSettings =
                null,
            global::Pine.Value<float>? @fallbackDpi = null,
            global::Pine.Value<bool>? @forceGammaRendering = null,
            global::Pine.Value<global::UnityEngine.HideFlags>? @hideFlags = null,
            global::Pine.Value<float>? @match = null,
            global::Pine.Value<string>? @name = null,
            global::Pine.Value<float>? @referenceDpi = null,
            global::Pine.Value<global::UnityEngine.Vector2Int>? @referenceResolution = null,
            global::Pine.Value<float>? @referenceSpritePixelsPerUnit = null,
            global::Pine.Value<float>? @scale = null,
            global::Pine.Value<global::UnityEngine.UIElements.PanelScaleMode>? @scaleMode = null,
            global::Pine.Value<global::UnityEngine.UIElements.PanelScreenMatchMode>? @screenMatchMode =
                null,
            global::Pine.Value<float>? @sortingOrder = null,
            global::Pine.Value<int>? @targetDisplay = null,
            global::Pine.Value<global::UnityEngine.RenderTexture>? @targetTexture = null,
            global::Pine.Value<global::UnityEngine.UIElements.PanelTextSettings>? @textSettings =
                null,
            global::Pine.Value<global::UnityEngine.UIElements.TextureSlotCount>? @textureSlotCount =
                null,
            global::Pine.Value<global::UnityEngine.UIElements.ThemeStyleSheet>? @themeStyleSheet =
                null,
            global::Pine.Value<uint>? @vertexBudget = null
#if PINE_UNITY_6000_3_25_OR_NEWER
            ,
            global::Pine.Value<global::UnityEngine.UIElements.PanelRenderMode>? @renderMode = null
#endif
        ) =>
            native =>
            {
                var node =
                    global::Pine.UIToolkit.Node.Current ?? new Node(null, Core.RequireScope());
                Prop(
                    native,
                    node,
                    "forceGammaRendering",
                    @forceGammaRendering,
                    (item, v) => item.@forceGammaRendering = v
                );
                Prop(
                    native,
                    node,
                    "textSettings",
                    @textSettings,
                    (item, v) => item.@textSettings = v
                );
                Prop(
                    native,
                    node,
                    "themeStyleSheet",
                    @themeStyleSheet,
                    (item, v) => item.@themeStyleSheet = v
                );
                Prop(
                    native,
                    node,
                    "targetTexture",
                    @targetTexture,
                    (item, v) => item.@targetTexture = v
                );
                Prop(native, node, "scaleMode", @scaleMode, (item, v) => item.@scaleMode = v);
                Prop(
                    native,
                    node,
                    "referenceSpritePixelsPerUnit",
                    @referenceSpritePixelsPerUnit,
                    (item, v) => item.@referenceSpritePixelsPerUnit = v
                );
                Prop(native, node, "scale", @scale, (item, v) => item.@scale = v);
                Prop(
                    native,
                    node,
                    "referenceDpi",
                    @referenceDpi,
                    (item, v) => item.@referenceDpi = v
                );
                Prop(native, node, "fallbackDpi", @fallbackDpi, (item, v) => item.@fallbackDpi = v);
                Prop(
                    native,
                    node,
                    "referenceResolution",
                    @referenceResolution,
                    (item, v) => item.@referenceResolution = v
                );
                Prop(
                    native,
                    node,
                    "screenMatchMode",
                    @screenMatchMode,
                    (item, v) => item.@screenMatchMode = v
                );
                Prop(native, node, "match", @match, (item, v) => item.@match = v);
                Prop(
                    native,
                    node,
                    "sortingOrder",
                    @sortingOrder,
                    (item, v) => item.@sortingOrder = v
                );
                Prop(
                    native,
                    node,
                    "targetDisplay",
                    @targetDisplay,
                    (item, v) => item.@targetDisplay = v
                );
                Prop(
                    native,
                    node,
                    "bindingLogLevel",
                    @bindingLogLevel,
                    (item, v) => item.@bindingLogLevel = v
                );
                Prop(
                    native,
                    node,
                    "clearDepthStencil",
                    @clearDepthStencil,
                    (item, v) => item.@clearDepthStencil = v
                );
                Prop(native, node, "clearColor", @clearColor, (item, v) => item.@clearColor = v);
                Prop(
                    native,
                    node,
                    "colorClearValue",
                    @colorClearValue.HasValue
                        ? (global::Pine.Value<global::UnityEngine.Color>?)
                            @colorClearValue.Value.Value
                        : null,
                    (item, v) => item.@colorClearValue = v
                );
                Prop(
                    native,
                    node,
                    "vertexBudget",
                    @vertexBudget,
                    (item, v) => item.@vertexBudget = v
                );
                Prop(
                    native,
                    node,
                    "textureSlotCount",
                    @textureSlotCount,
                    (item, v) => item.@textureSlotCount = v
                );
                Prop(
                    native,
                    node,
                    "dynamicAtlasSettings",
                    @dynamicAtlasSettings,
                    (item, v) => item.@dynamicAtlasSettings = v
                );
                Prop(native, node, "name", @name, (item, v) => item.@name = v);
                Prop(native, node, "hideFlags", @hideFlags, (item, v) => item.@hideFlags = v);
#if PINE_UNITY_6000_3_25_OR_NEWER
                Prop(native, node, "renderMode", @renderMode, (item, v) => item.@renderMode = v);
#endif
            };

        public static Action<global::UnityEngine.UIElements.UIDocument> UIDocument(
            global::Pine.Value<bool>? @enabled = null,
            global::Pine.Value<global::UnityEngine.HideFlags>? @hideFlags = null,
            global::Pine.Value<string>? @name = null,
            global::Pine.Value<global::UnityEngine.UIElements.PanelSettings>? @panelSettings = null,
            global::Pine.Value<global::UnityEngine.UIElements.Pivot>? @pivot = null,
            global::Pine.Value<global::UnityEngine.UIElements.PivotReferenceSize>? @pivotReferenceSize =
                null,
            global::Pine.Value<global::UnityEngine.UIElements.Position>? @position = null,
            global::Pine.Value<float>? @sortingOrder = null,
            global::Pine.Value<string>? @tag = null,
            global::Pine.Value<bool>? @useGUILayout = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualTreeAsset>? @visualTreeAsset =
                null,
            Vector2Value? @worldSpaceSize = null,
            global::Pine.Value<global::UnityEngine.UIElements.UIDocument.WorldSpaceSizeMode>? @worldSpaceSizeMode =
                null
#if UNITY_EDITOR
            ,
            Value<bool>? runInEditMode = null
#endif
        ) =>
            native =>
            {
                var node =
                    global::Pine.UIToolkit.Node.Current ?? new Node(null, Core.RequireScope());
                Prop(
                    native,
                    node,
                    "panelSettings",
                    @panelSettings,
                    (item, v) => item.@panelSettings = v
                );
                Prop(
                    native,
                    node,
                    "visualTreeAsset",
                    @visualTreeAsset,
                    (item, v) => item.@visualTreeAsset = v
                );
                Prop(native, node, "position", @position, (item, v) => item.@position = v);
                Prop(
                    native,
                    node,
                    "worldSpaceSizeMode",
                    @worldSpaceSizeMode,
                    (item, v) => item.@worldSpaceSizeMode = v
                );
                Prop(
                    native,
                    node,
                    "worldSpaceSize",
                    @worldSpaceSize.HasValue
                        ? (global::Pine.Value<global::UnityEngine.Vector2>?)
                            @worldSpaceSize.Value.Value
                        : null,
                    (item, v) => item.@worldSpaceSize = v
                );
                Prop(
                    native,
                    node,
                    "pivotReferenceSize",
                    @pivotReferenceSize,
                    (item, v) => item.@pivotReferenceSize = v
                );
                Prop(native, node, "pivot", @pivot, (item, v) => item.@pivot = v);
                Prop(
                    native,
                    node,
                    "sortingOrder",
                    @sortingOrder,
                    (item, v) => item.@sortingOrder = v
                );
                Prop(
                    native,
                    node,
                    "useGUILayout",
                    @useGUILayout,
                    (item, v) => item.@useGUILayout = v
                );
                Prop(native, node, "enabled", @enabled, (item, v) => item.@enabled = v);
                Prop(native, node, "tag", @tag, (item, v) => item.@tag = v);
                Prop(native, node, "name", @name, (item, v) => item.@name = v);
                Prop(native, node, "hideFlags", @hideFlags, (item, v) => item.@hideFlags = v);
#if UNITY_EDITOR
                Prop(
                    native,
                    node,
                    "runInEditMode",
                    runInEditMode,
                    (item, v) => item.runInEditMode = v
                );
#endif
            };

#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.ClickSelector ClickSelector(
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.ClickSelector();
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.ContentDragger ContentDragger(
            global::Pine.Value<bool>? @clampToParentEdges = null,
            Vector2Value? @panSpeed = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.ContentDragger();
            Prop(
                native,
                node,
                "panSpeed",
                @panSpeed.HasValue
                    ? (global::Pine.Value<global::UnityEngine.Vector2>?)@panSpeed.Value.Value
                    : null,
                (item, v) => item.@panSpeed = v
            );
            Prop(
                native,
                node,
                "clampToParentEdges",
                @clampToParentEdges,
                (item, v) => item.@clampToParentEdges = v
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.ContentZoomer ContentZoomer(
            global::Pine.Value<float>? @maxScale = null,
            global::Pine.Value<float>? @minScale = null,
            global::Pine.Value<float>? @referenceScale = null,
            global::Pine.Value<float>? @scaleStep = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.ContentZoomer();
            Prop(
                native,
                node,
                "referenceScale",
                @referenceScale,
                (item, v) => item.@referenceScale = v
            );
            Prop(native, node, "minScale", @minScale, (item, v) => item.@minScale = v);
            Prop(native, node, "maxScale", @maxScale, (item, v) => item.@maxScale = v);
            Prop(native, node, "scaleStep", @scaleStep, (item, v) => item.@scaleStep = v);
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.Dragger Dragger(
            global::Pine.Value<bool>? @clampToParentEdges = null,
            Vector2Value? @panSpeed = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.Dragger();
            Prop(
                native,
                node,
                "panSpeed",
                @panSpeed.HasValue
                    ? (global::Pine.Value<global::UnityEngine.Vector2>?)@panSpeed.Value.Value
                    : null,
                (item, v) => item.@panSpeed = v
            );
            Prop(
                native,
                node,
                "clampToParentEdges",
                @clampToParentEdges,
                (item, v) => item.@clampToParentEdges = v
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.EdgeConnector<TEdge> EdgeConnector<TEdge>(
            global::UnityEditor.Experimental.GraphView.IEdgeConnectorListener @listener,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
            where TEdge : global::UnityEditor.Experimental.GraphView.Edge, new()
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.EdgeConnector<TEdge>(
                @listener
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.EdgeManipulator EdgeManipulator(
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.EdgeManipulator();
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.FreehandSelector FreehandSelector(
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.FreehandSelector();
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.RectangleSelector RectangleSelector(
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.RectangleSelector();
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.SelectionDragger SelectionDragger(
            global::Pine.Value<bool>? @clampToParentEdges = null,
            Vector2Value? @panSpeed = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.SelectionDragger();
            Prop(
                native,
                node,
                "panSpeed",
                @panSpeed.HasValue
                    ? (global::Pine.Value<global::UnityEngine.Vector2>?)@panSpeed.Value.Value
                    : null,
                (item, v) => item.@panSpeed = v
            );
            Prop(
                native,
                node,
                "clampToParentEdges",
                @clampToParentEdges,
                (item, v) => item.@clampToParentEdges = v
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.SelectionDropper SelectionDropper(
            global::Pine.Value<global::UnityEngine.UIElements.MouseButton>? @activateButton = null,
            global::Pine.Value<bool>? @clampToParentEdges = null,
            Vector2Value? @panSpeed = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.SelectionDropper();
            Prop(
                native,
                node,
                "panSpeed",
                @panSpeed.HasValue
                    ? (global::Pine.Value<global::UnityEngine.Vector2>?)@panSpeed.Value.Value
                    : null,
                (item, v) => item.@panSpeed = v
            );
            Prop(
                native,
                node,
                "activateButton",
                @activateButton,
                (item, v) => item.@activateButton = v
            );
            Prop(
                native,
                node,
                "clampToParentEdges",
                @clampToParentEdges,
                (item, v) => item.@clampToParentEdges = v
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif
#if UNITY_EDITOR
        public static global::UnityEditor.Experimental.GraphView.ShortcutHandler ShortcutHandler(
            global::System.Collections.Generic.Dictionary<
                global::UnityEngine.Event,
                global::UnityEditor.Experimental.GraphView.ShortcutDelegate
            > @dictionary,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEditor.Experimental.GraphView.ShortcutHandler(
                @dictionary
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }
#endif

        public static global::UnityEngine.UIElements.Clickable Clickable(
            global::System.Action @handler,
            long @delay,
            long @interval,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null,
            global::System.Action<global::UnityEngine.UIElements.EventBase> @onClickedWithEventInfo =
                null,
            global::System.Action @onClicked = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.Clickable(
                (
                    @handler == null
                        ? null
                        : (global::System.Action)(() => Scoped(node, () => @handler()))
                ),
                @delay,
                @interval
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            if (@onClickedWithEventInfo != null)
                Listen(
                    node,
                    (global::System.Action<global::UnityEngine.UIElements.EventBase>)(
                        (@argument0) => Scoped(node, () => @onClickedWithEventInfo(@argument0))
                    ),
                    handler => native.@clickedWithEventInfo += handler,
                    handler => native.@clickedWithEventInfo -= handler
                );
            if (@onClicked != null)
                Listen(
                    node,
                    (global::System.Action)(() => Scoped(node, () => @onClicked())),
                    handler => native.@clicked += handler,
                    handler => native.@clicked -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.Clickable Clickable(
            global::System.Action<global::UnityEngine.UIElements.EventBase> @handler,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null,
            global::System.Action<global::UnityEngine.UIElements.EventBase> @onClickedWithEventInfo =
                null,
            global::System.Action @onClicked = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.Clickable(
                (
                    @handler == null
                        ? null
                        : (global::System.Action<global::UnityEngine.UIElements.EventBase>)(
                            (@argument0) => Scoped(node, () => @handler(@argument0))
                        )
                )
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            if (@onClickedWithEventInfo != null)
                Listen(
                    node,
                    (global::System.Action<global::UnityEngine.UIElements.EventBase>)(
                        (@argument0) => Scoped(node, () => @onClickedWithEventInfo(@argument0))
                    ),
                    handler => native.@clickedWithEventInfo += handler,
                    handler => native.@clickedWithEventInfo -= handler
                );
            if (@onClicked != null)
                Listen(
                    node,
                    (global::System.Action)(() => Scoped(node, () => @onClicked())),
                    handler => native.@clicked += handler,
                    handler => native.@clicked -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.Clickable Clickable(
            global::System.Action @handler,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null,
            global::System.Action<global::UnityEngine.UIElements.EventBase> @onClickedWithEventInfo =
                null,
            global::System.Action @onClicked = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.Clickable(
                (
                    @handler == null
                        ? null
                        : (global::System.Action)(() => Scoped(node, () => @handler()))
                )
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            if (@onClickedWithEventInfo != null)
                Listen(
                    node,
                    (global::System.Action<global::UnityEngine.UIElements.EventBase>)(
                        (@argument0) => Scoped(node, () => @onClickedWithEventInfo(@argument0))
                    ),
                    handler => native.@clickedWithEventInfo += handler,
                    handler => native.@clickedWithEventInfo -= handler
                );
            if (@onClicked != null)
                Listen(
                    node,
                    (global::System.Action)(() => Scoped(node, () => @onClicked())),
                    handler => native.@clicked += handler,
                    handler => native.@clicked -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.ContextualMenuManipulator ContextualMenuManipulator(
            global::System.Action<global::UnityEngine.UIElements.ContextualMenuPopulateEvent> @menuBuilder,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.ContextualMenuManipulator(
                (
                    @menuBuilder == null
                        ? null
                        : (global::System.Action<global::UnityEngine.UIElements.ContextualMenuPopulateEvent>)(
                            (@argument0) => Scoped(node, () => @menuBuilder(@argument0))
                        )
                )
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }

        public static global::UnityEngine.UIElements.DataBinding DataBinding(
            global::Pine.Value<global::UnityEngine.UIElements.BindingMode>? @bindingMode = null,
            global::Pine.Value<object>? @dataSource = null,
            PropertyPathValue? @dataSourcePath = null,
            global::Pine.Value<global::System.Type>? @dataSourceType = null,
            global::Pine.Value<global::UnityEngine.UIElements.BindingUpdateTrigger>? @updateTrigger =
                null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.DataBinding();
            Prop(native, node, "dataSource", @dataSource, (item, v) => item.@dataSource = v);
            Prop(
                native,
                node,
                "dataSourceType",
                @dataSourceType,
                (item, v) => item.@dataSourceType = v
            );
            Prop(
                native,
                node,
                "dataSourcePath",
                @dataSourcePath.HasValue
                    ? (global::Pine.Value<global::Unity.Properties.PropertyPath>?)
                        @dataSourcePath.Value.Value
                    : null,
                (item, v) => item.@dataSourcePath = v
            );
            Prop(native, node, "bindingMode", @bindingMode, (item, v) => item.@bindingMode = v);
            Prop(
                native,
                node,
                "updateTrigger",
                @updateTrigger,
                (item, v) => item.@updateTrigger = v
            );
            return native;
        }

        public static global::UnityEngine.UIElements.KeyboardNavigationManipulator KeyboardNavigationManipulator(
            global::System.Action<
                global::UnityEngine.UIElements.KeyboardNavigationOperation,
                global::UnityEngine.UIElements.EventBase
            > @action,
            global::Pine.Value<global::UnityEngine.UIElements.VisualElement>? @target = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.KeyboardNavigationManipulator(
                (
                    @action == null
                        ? null
                        : (global::System.Action<
                            global::UnityEngine.UIElements.KeyboardNavigationOperation,
                            global::UnityEngine.UIElements.EventBase
                        >)(
                            (@argument0, @argument1) =>
                                Scoped(node, () => @action(@argument0, @argument1))
                        )
                )
            );
            Prop(native, node, "target", @target, (item, v) => item.@target = v);
            return native;
        }

        public static global::UnityEngine.UIElements.Column Column(
            global::System.Action<global::UnityEngine.UIElements.VisualElement, int> @bindCell =
                null,
            global::Pine.Value<global::System.Action<
                global::UnityEngine.UIElements.VisualElement,
                int
            >>? @bindCellValue = null,
            global::System.Action<global::UnityEngine.UIElements.VisualElement> @bindHeader = null,
            global::Pine.Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>? @bindHeaderValue =
                null,
            global::Pine.Value<string>? @bindingPath = null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualTreeAsset>? @cellTemplate =
                null,
            global::System.Comparison<int> @comparison = null,
            global::Pine.Value<global::System.Comparison<int>>? @comparisonValue = null,
            global::System.Action<global::UnityEngine.UIElements.VisualElement> @destroyCell = null,
            global::Pine.Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>? @destroyCellValue =
                null,
            global::System.Action<global::UnityEngine.UIElements.VisualElement> @destroyHeader =
                null,
            global::Pine.Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>? @destroyHeaderValue =
                null,
            global::Pine.Value<global::UnityEngine.UIElements.VisualTreeAsset>? @headerTemplate =
                null,
            BackgroundValue? @icon = null,
            global::System.Func<global::UnityEngine.UIElements.VisualElement> @makeCell = null,
            global::Pine.Value<global::System.Func<global::UnityEngine.UIElements.VisualElement>>? @makeCellValue =
                null,
            global::System.Func<global::UnityEngine.UIElements.VisualElement> @makeHeader = null,
            global::Pine.Value<global::System.Func<global::UnityEngine.UIElements.VisualElement>>? @makeHeaderValue =
                null,
            LengthValue? @maxWidth = null,
            LengthValue? @minWidth = null,
            global::Pine.Value<string>? @name = null,
            global::Pine.Value<bool>? @optional = null,
            global::Pine.Value<bool>? @resizable = null,
            global::Pine.Value<bool>? @sortable = null,
            global::Pine.Value<bool>? @stretchable = null,
            global::Pine.Value<string>? @title = null,
            global::System.Action<global::UnityEngine.UIElements.VisualElement, int> @unbindCell =
                null,
            global::Pine.Value<global::System.Action<
                global::UnityEngine.UIElements.VisualElement,
                int
            >>? @unbindCellValue = null,
            global::System.Action<global::UnityEngine.UIElements.VisualElement> @unbindHeader =
                null,
            global::Pine.Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>? @unbindHeaderValue =
                null,
            global::Pine.Value<bool>? @visible = null,
            LengthValue? @width = null,
            global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs> @onPropertyChanged =
                null,
            Cell cell = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.Column();
            Prop(native, node, "name", @name, (item, v) => item.@name = v);
            Prop(native, node, "title", @title, (item, v) => item.@title = v);
            Prop(
                native,
                node,
                "icon",
                @icon.HasValue
                    ? (global::Pine.Value<global::UnityEngine.UIElements.Background>?)
                        @icon.Value.Value
                    : null,
                (item, v) => item.@icon = v
            );
            if (@comparison != null)
                CallbackProp<global::UnityEngine.UIElements.Column, global::System.Comparison<int>>(
                    native,
                    node,
                    "comparison",
                    new Value<global::System.Comparison<int>>(
                        (global::System.Comparison<int>)(
                            (@argument0, @argument1) =>
                                Scoped(node, () => @comparison(@argument0, @argument1))
                        )
                    ),
                    item => item.@comparison,
                    (item, v) => item.@comparison = v
                );
            CallbackProp(
                native,
                node,
                "comparison",
                @comparisonValue,
                item => item.@comparison,
                (item, v) =>
                    item.@comparison =
                        v == null
                            ? null
                            : (global::System.Comparison<int>)(
                                (@argument0, @argument1) =>
                                    Scoped(node, () => v(@argument0, @argument1))
                            )
            );
            Prop(native, node, "visible", @visible, (item, v) => item.@visible = v);
            Prop(
                native,
                node,
                "width",
                @width.HasValue
                    ? (global::Pine.Value<global::UnityEngine.UIElements.Length>?)@width.Value.Value
                    : null,
                (item, v) => item.@width = v
            );
            Prop(
                native,
                node,
                "minWidth",
                @minWidth.HasValue
                    ? (global::Pine.Value<global::UnityEngine.UIElements.Length>?)
                        @minWidth.Value.Value
                    : null,
                (item, v) => item.@minWidth = v
            );
            Prop(
                native,
                node,
                "maxWidth",
                @maxWidth.HasValue
                    ? (global::Pine.Value<global::UnityEngine.UIElements.Length>?)
                        @maxWidth.Value.Value
                    : null,
                (item, v) => item.@maxWidth = v
            );
            Prop(native, node, "sortable", @sortable, (item, v) => item.@sortable = v);
            Prop(native, node, "stretchable", @stretchable, (item, v) => item.@stretchable = v);
            Prop(native, node, "optional", @optional, (item, v) => item.@optional = v);
            Prop(native, node, "resizable", @resizable, (item, v) => item.@resizable = v);
            Prop(native, node, "bindingPath", @bindingPath, (item, v) => item.@bindingPath = v);
            Prop(
                native,
                node,
                "headerTemplate",
                @headerTemplate,
                (item, v) => item.@headerTemplate = v
            );
            Prop(native, node, "cellTemplate", @cellTemplate, (item, v) => item.@cellTemplate = v);
            if (@makeHeader != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Func<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "makeHeader",
                    new Value<global::System.Func<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Func<global::UnityEngine.UIElements.VisualElement>)(
                            () => Scoped(node, () => @makeHeader())
                        )
                    ),
                    item => item.@makeHeader,
                    (item, v) => item.@makeHeader = v
                );
            CallbackProp(
                native,
                node,
                "makeHeader",
                @makeHeaderValue,
                item => item.@makeHeader,
                (item, v) =>
                    item.@makeHeader =
                        v == null
                            ? null
                            : (global::System.Func<global::UnityEngine.UIElements.VisualElement>)(
                                () => Scoped(node, () => v())
                            )
            );
            if (@bindHeader != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "bindHeader",
                    new Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                            (@argument0) => Scoped(node, () => @bindHeader(@argument0))
                        )
                    ),
                    item => item.@bindHeader,
                    (item, v) => item.@bindHeader = v
                );
            CallbackProp(
                native,
                node,
                "bindHeader",
                @bindHeaderValue,
                item => item.@bindHeader,
                (item, v) =>
                    item.@bindHeader =
                        v == null
                            ? null
                            : (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                                (@argument0) => Scoped(node, () => v(@argument0))
                            )
            );
            if (@unbindHeader != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "unbindHeader",
                    new Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                            (@argument0) => Scoped(node, () => @unbindHeader(@argument0))
                        )
                    ),
                    item => item.@unbindHeader,
                    (item, v) => item.@unbindHeader = v
                );
            CallbackProp(
                native,
                node,
                "unbindHeader",
                @unbindHeaderValue,
                item => item.@unbindHeader,
                (item, v) =>
                    item.@unbindHeader =
                        v == null
                            ? null
                            : (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                                (@argument0) => Scoped(node, () => v(@argument0))
                            )
            );
            if (@destroyHeader != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "destroyHeader",
                    new Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                            (@argument0) => Scoped(node, () => @destroyHeader(@argument0))
                        )
                    ),
                    item => item.@destroyHeader,
                    (item, v) => item.@destroyHeader = v
                );
            CallbackProp(
                native,
                node,
                "destroyHeader",
                @destroyHeaderValue,
                item => item.@destroyHeader,
                (item, v) =>
                    item.@destroyHeader =
                        v == null
                            ? null
                            : (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                                (@argument0) => Scoped(node, () => v(@argument0))
                            )
            );
            if (@makeCell != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Func<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "makeCell",
                    new Value<global::System.Func<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Func<global::UnityEngine.UIElements.VisualElement>)(
                            () => Scoped(node, () => @makeCell())
                        )
                    ),
                    item => item.@makeCell,
                    (item, v) => item.@makeCell = v
                );
            CallbackProp(
                native,
                node,
                "makeCell",
                @makeCellValue,
                item => item.@makeCell,
                (item, v) =>
                    item.@makeCell =
                        v == null
                            ? null
                            : (global::System.Func<global::UnityEngine.UIElements.VisualElement>)(
                                () => Scoped(node, () => v())
                            )
            );
            if (@bindCell != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement, int>
                >(
                    native,
                    node,
                    "bindCell",
                    new Value<global::System.Action<
                        global::UnityEngine.UIElements.VisualElement,
                        int
                    >>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement, int>)(
                            (@argument0, @argument1) =>
                                Scoped(node, () => @bindCell(@argument0, @argument1))
                        )
                    ),
                    item => item.@bindCell,
                    (item, v) => item.@bindCell = v
                );
            CallbackProp(
                native,
                node,
                "bindCell",
                @bindCellValue,
                item => item.@bindCell,
                (item, v) =>
                    item.@bindCell =
                        v == null
                            ? null
                            : (global::System.Action<
                                global::UnityEngine.UIElements.VisualElement,
                                int
                            >)(
                                (@argument0, @argument1) =>
                                    Scoped(node, () => v(@argument0, @argument1))
                            )
            );
            if (@unbindCell != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement, int>
                >(
                    native,
                    node,
                    "unbindCell",
                    new Value<global::System.Action<
                        global::UnityEngine.UIElements.VisualElement,
                        int
                    >>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement, int>)(
                            (@argument0, @argument1) =>
                                Scoped(node, () => @unbindCell(@argument0, @argument1))
                        )
                    ),
                    item => item.@unbindCell,
                    (item, v) => item.@unbindCell = v
                );
            CallbackProp(
                native,
                node,
                "unbindCell",
                @unbindCellValue,
                item => item.@unbindCell,
                (item, v) =>
                    item.@unbindCell =
                        v == null
                            ? null
                            : (global::System.Action<
                                global::UnityEngine.UIElements.VisualElement,
                                int
                            >)(
                                (@argument0, @argument1) =>
                                    Scoped(node, () => v(@argument0, @argument1))
                            )
            );
            if (@destroyCell != null)
                CallbackProp<
                    global::UnityEngine.UIElements.Column,
                    global::System.Action<global::UnityEngine.UIElements.VisualElement>
                >(
                    native,
                    node,
                    "destroyCell",
                    new Value<global::System.Action<global::UnityEngine.UIElements.VisualElement>>(
                        (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                            (@argument0) => Scoped(node, () => @destroyCell(@argument0))
                        )
                    ),
                    item => item.@destroyCell,
                    (item, v) => item.@destroyCell = v
                );
            CallbackProp(
                native,
                node,
                "destroyCell",
                @destroyCellValue,
                item => item.@destroyCell,
                (item, v) =>
                    item.@destroyCell =
                        v == null
                            ? null
                            : (global::System.Action<global::UnityEngine.UIElements.VisualElement>)(
                                (@argument0) => Scoped(node, () => v(@argument0))
                            )
            );
            if (@onPropertyChanged != null)
                Listen(
                    node,
                    (global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs>)(
                        (@argument0, @argument1) =>
                            Scoped(node, () => @onPropertyChanged(@argument0, @argument1))
                    ),
                    handler => native.@propertyChanged += handler,
                    handler => native.@propertyChanged -= handler
                );
            Cells(node, native, cell);
            return native;
        }

        public static global::UnityEngine.UIElements.Columns Columns(
            global::Pine.Value<string>? @primaryColumnName = null,
            global::Pine.Value<bool>? @reorderable = null,
            global::Pine.Value<bool>? @resizable = null,
            global::Pine.Value<bool>? @resizePreview = null,
            global::Pine.Value<global::UnityEngine.UIElements.Columns.StretchMode>? @stretchMode =
                null,
            global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs> @onPropertyChanged =
                null,
            global::UnityEngine.UIElements.Column[] items = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.Columns();
            Prop(
                native,
                node,
                "primaryColumnName",
                @primaryColumnName,
                (item, v) => item.@primaryColumnName = v
            );
            Prop(native, node, "reorderable", @reorderable, (item, v) => item.@reorderable = v);
            Prop(native, node, "resizable", @resizable, (item, v) => item.@resizable = v);
            Prop(
                native,
                node,
                "resizePreview",
                @resizePreview,
                (item, v) => item.@resizePreview = v
            );
            Prop(native, node, "stretchMode", @stretchMode, (item, v) => item.@stretchMode = v);
            if (@onPropertyChanged != null)
                Listen(
                    node,
                    (global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs>)(
                        (@argument0, @argument1) =>
                            Scoped(node, () => @onPropertyChanged(@argument0, @argument1))
                    ),
                    handler => native.@propertyChanged += handler,
                    handler => native.@propertyChanged -= handler
                );
            Columns(node, native, items);
            return native;
        }

        public static global::UnityEngine.UIElements.ConverterGroup ConverterGroup(
            string @id,
            string @displayName,
            string @description
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.ConverterGroup(
                @id,
                @displayName,
                @description
            );
            return native;
        }

        public static global::UnityEngine.UIElements.DropdownMenu DropdownMenu(
            global::Pine.Value<bool>? @allowDuplicateNames = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.DropdownMenu();
            Prop(
                native,
                node,
                "allowDuplicateNames",
                @allowDuplicateNames,
                (item, v) => item.@allowDuplicateNames = v
            );
            return native;
        }

        public static global::UnityEngine.UIElements.DropdownMenuAction DropdownMenuAction(
            string @actionName,
            global::System.Action<global::UnityEngine.UIElements.DropdownMenuAction> @actionCallback,
            global::System.Func<
                global::UnityEngine.UIElements.DropdownMenuAction,
                global::UnityEngine.UIElements.DropdownMenuAction.Status
            > @actionStatusCallback,
            object @userData
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.DropdownMenuAction(
                @actionName,
                (
                    @actionCallback == null
                        ? null
                        : (global::System.Action<global::UnityEngine.UIElements.DropdownMenuAction>)(
                            (@argument0) => Scoped(node, () => @actionCallback(@argument0))
                        )
                ),
                (
                    @actionStatusCallback == null
                        ? null
                        : (global::System.Func<
                            global::UnityEngine.UIElements.DropdownMenuAction,
                            global::UnityEngine.UIElements.DropdownMenuAction.Status
                        >)((@argument0) => Scoped(node, () => @actionStatusCallback(@argument0)))
                ),
                @userData
            );
            return native;
        }

        public static global::UnityEngine.UIElements.DropdownMenuSeparator DropdownMenuSeparator(
            string @subMenuPath
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.DropdownMenuSeparator(@subMenuPath);
            return native;
        }

        public static global::UnityEngine.UIElements.DynamicAtlasSettings DynamicAtlasSettings(
            global::Pine.Value<global::UnityEngine.UIElements.DynamicAtlasFilters>? @activeFilters =
                null,
            global::UnityEngine.UIElements.DynamicAtlasCustomFilter @customFilter = null,
            global::Pine.Value<global::UnityEngine.UIElements.DynamicAtlasCustomFilter>? @customFilterValue =
                null,
            global::Pine.Value<int>? @maxAtlasSize = null,
            global::Pine.Value<int>? @maxSubTextureSize = null,
            global::Pine.Value<int>? @minAtlasSize = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.DynamicAtlasSettings();
            Prop(native, node, "minAtlasSize", @minAtlasSize, (item, v) => item.@minAtlasSize = v);
            Prop(native, node, "maxAtlasSize", @maxAtlasSize, (item, v) => item.@maxAtlasSize = v);
            Prop(
                native,
                node,
                "maxSubTextureSize",
                @maxSubTextureSize,
                (item, v) => item.@maxSubTextureSize = v
            );
            Prop(
                native,
                node,
                "activeFilters",
                @activeFilters,
                (item, v) => item.@activeFilters = v
            );
            if (@customFilter != null)
                CallbackProp<
                    global::UnityEngine.UIElements.DynamicAtlasSettings,
                    global::UnityEngine.UIElements.DynamicAtlasCustomFilter
                >(
                    native,
                    node,
                    "customFilter",
                    new Value<global::UnityEngine.UIElements.DynamicAtlasCustomFilter>(
                        (global::UnityEngine.UIElements.DynamicAtlasCustomFilter)(
                            (
                                global::UnityEngine.Texture2D @argument0,
                                ref global::UnityEngine.UIElements.DynamicAtlasFilters @argument1
                            ) =>
                            {
                                global::UnityEngine.UIElements.DynamicAtlasFilters local1 =
                                    @argument1;
                                try
                                {
                                    return Scoped(
                                        node,
                                        () => @customFilter(@argument0, ref local1)
                                    );
                                }
                                finally
                                {
                                    @argument1 = local1;
                                }
                            }
                        )
                    ),
                    item => item.@customFilter,
                    (item, v) => item.@customFilter = v
                );
            CallbackProp(
                native,
                node,
                "customFilter",
                @customFilterValue,
                item => item.@customFilter,
                (item, v) =>
                    item.@customFilter =
                        v == null
                            ? null
                            : (global::UnityEngine.UIElements.DynamicAtlasCustomFilter)(
                                (
                                    global::UnityEngine.Texture2D @argument0,
                                    ref global::UnityEngine.UIElements.DynamicAtlasFilters @argument1
                                ) =>
                                {
                                    global::UnityEngine.UIElements.DynamicAtlasFilters local1 =
                                        @argument1;
                                    try
                                    {
                                        return Scoped(node, () => v(@argument0, ref local1));
                                    }
                                    finally
                                    {
                                        @argument1 = local1;
                                    }
                                }
                            )
            );
            return native;
        }

        public static global::UnityEngine.UIElements.SortColumnDescription SortColumnDescription(
            global::Pine.Value<int>? @columnIndex = null,
            global::Pine.Value<string>? @columnName = null,
            global::Pine.Value<global::UnityEngine.UIElements.SortDirection>? @direction = null,
            global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs> @onPropertyChanged =
                null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.SortColumnDescription();
            Prop(native, node, "columnName", @columnName, (item, v) => item.@columnName = v);
            Prop(native, node, "columnIndex", @columnIndex, (item, v) => item.@columnIndex = v);
            Prop(native, node, "direction", @direction, (item, v) => item.@direction = v);
            if (@onPropertyChanged != null)
                Listen(
                    node,
                    (global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs>)(
                        (@argument0, @argument1) =>
                            Scoped(node, () => @onPropertyChanged(@argument0, @argument1))
                    ),
                    handler => native.@propertyChanged += handler,
                    handler => native.@propertyChanged -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.SortColumnDescription SortColumnDescription(
            int @columnIndex,
            global::UnityEngine.UIElements.SortDirection @direction,
            global::Pine.Value<string>? @columnName = null,
            global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs> @onPropertyChanged =
                null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.SortColumnDescription(
                @columnIndex,
                @direction
            );
            Prop(native, node, "columnName", @columnName, (item, v) => item.@columnName = v);
            if (@onPropertyChanged != null)
                Listen(
                    node,
                    (global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs>)(
                        (@argument0, @argument1) =>
                            Scoped(node, () => @onPropertyChanged(@argument0, @argument1))
                    ),
                    handler => native.@propertyChanged += handler,
                    handler => native.@propertyChanged -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.SortColumnDescription SortColumnDescription(
            string @columnName,
            global::UnityEngine.UIElements.SortDirection @direction,
            global::Pine.Value<int>? @columnIndex = null,
            global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs> @onPropertyChanged =
                null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.SortColumnDescription(
                @columnName,
                @direction
            );
            Prop(native, node, "columnIndex", @columnIndex, (item, v) => item.@columnIndex = v);
            if (@onPropertyChanged != null)
                Listen(
                    node,
                    (global::System.EventHandler<global::UnityEngine.UIElements.BindablePropertyChangedEventArgs>)(
                        (@argument0, @argument1) =>
                            Scoped(node, () => @onPropertyChanged(@argument0, @argument1))
                    ),
                    handler => native.@propertyChanged += handler,
                    handler => native.@propertyChanged -= handler
                );
            return native;
        }

        public static global::UnityEngine.UIElements.SortColumnDescriptions SortColumnDescriptions(
            global::UnityEngine.UIElements.SortColumnDescription[] items = null
        )
        {
            var node = new Node(null, Core.RequireScope());
            var native = new global::UnityEngine.UIElements.SortColumnDescriptions();
            SortColumns(node, native, items);
            return native;
        }
    }
}
