using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal static class SharedApi
{
    internal static void Generate(string package)
    {
        var members = new List<MemberDeclarationSyntax>();
        foreach (var name in new[] { "Pine.cs", "Dynamic.cs", "Animation.cs", "Ref.cs" })
        {
            var root = CSharpSyntaxTree
                .ParseText(File.ReadAllText(Path.Combine(package, "Runtime", name)))
                .GetRoot();
            foreach (
                var declaration in root.DescendantNodes()
                    .OfType<ClassDeclarationSyntax>()
                    .Where(c => c.Identifier.Text == "Core")
            )
                members.AddRange(
                    declaration.Members.Where(m =>
                        (m is MethodDeclarationSyntax or PropertyDeclarationSyntax)
                        && Modifiers(m)
                            .Any(t =>
                                t.IsKind(SyntaxKind.PublicKeyword)
                                || t.IsKind(SyntaxKind.InternalKeyword)
                            )
                        && Modifiers(m).Any(SyntaxKind.StaticKeyword)
                    )
                );
        }
        var output = new StringBuilder(
            "// <auto-generated/>\nusing System;\nusing System.Collections.Generic;\n\n"
        );
        foreach (var renderer in new[] { "uGUI", "UIToolkit" })
        {
            output
                .Append("namespace Pine.")
                .Append(renderer)
                .Append("\n{\n    public static partial class P\n    {\n");
            foreach (var member in members)
            {
                MemberDeclarationSyntax forwarded;
                if (member is MethodDeclarationSyntax method)
                {
                    var arguments = method.ParameterList.Parameters.Select(p =>
                        (
                            p.Modifiers.Any(SyntaxKind.RefKeyword) ? "ref "
                            : p.Modifiers.Any(SyntaxKind.OutKeyword) ? "out "
                            : ""
                        ) + p.Identifier.Text
                    );
                    var expression = SyntaxFactory.ParseExpression(
                        "global::Pine.Core."
                            + method.Identifier.Text
                            + method.TypeParameterList
                            + "("
                            + string.Join(", ", arguments)
                            + ")"
                    );
                    forwarded = method
                        .WithBody(null)
                        .WithExpressionBody(SyntaxFactory.ArrowExpressionClause(expression))
                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));
                }
                else
                {
                    var property = (PropertyDeclarationSyntax)member;
                    var access = "global::Pine.Core." + property.Identifier.Text;
                    var accessors = new List<AccessorDeclarationSyntax>
                    {
                        SyntaxFactory
                            .AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                            .WithExpressionBody(
                                SyntaxFactory.ArrowExpressionClause(
                                    SyntaxFactory.ParseExpression(access)
                                )
                            )
                            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    };
                    if (
                        property.AccessorList?.Accessors.Any(a =>
                            a.IsKind(SyntaxKind.SetAccessorDeclaration)
                        ) == true
                    )
                        accessors.Add(
                            SyntaxFactory
                                .AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                                .WithExpressionBody(
                                    SyntaxFactory.ArrowExpressionClause(
                                        SyntaxFactory.ParseExpression(access + " = value")
                                    )
                                )
                                .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                        );
                    forwarded = property
                        .WithExpressionBody(null)
                        .WithInitializer(null)
                        .WithSemicolonToken(default)
                        .WithAccessorList(
                            SyntaxFactory.AccessorList(SyntaxFactory.List(accessors))
                        );
                }
                output.Append(forwarded.NormalizeWhitespace().ToFullString()).Append('\n');
            }
            output.Append("    }\n}\n\n");
        }
        File.WriteAllText(Path.Combine(package, "Runtime", "SharedApi.g.cs"), output.ToString());
    }

    private static SyntaxTokenList Modifiers(MemberDeclarationSyntax member) =>
        member is MethodDeclarationSyntax method
            ? method.Modifiers
            : ((PropertyDeclarationSyntax)member).Modifiers;
}
