using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

sealed class ToolkitGenerator
{
    private readonly CSharpCompilation baseline,
        patch;
    private readonly JsonElement baselineJson,
        patchJson;
    private readonly StringBuilder factory = new();
    private static readonly SymbolDisplayFormat Format = SymbolDisplayFormat.FullyQualifiedFormat;
    public int FactoryCount,
        StyleCount;

    public ToolkitGenerator(
        CSharpCompilation baseline,
        CSharpCompilation patch,
        JsonElement baselineJson,
        JsonElement patchJson
    )
    {
        this.baseline = baseline;
        this.patch = patch;
        this.baselineJson = baselineJson;
        this.patchJson = patchJson;
    }

    private static string Type(ITypeSymbol type) => type.ToDisplayString(Format);

    private static bool Obsolete(ISymbol symbol) =>
        symbol
            .GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == "System.ObsoleteAttribute");

    private static string SymbolMetadataName(INamedTypeSymbol type) =>
        type.ContainingType != null
            ? SymbolMetadataName(type.ContainingType) + "+" + type.MetadataName
            : type.ContainingNamespace.ToDisplayString() + "." + type.MetadataName;

    private ISymbol[] PatchMembers(INamedTypeSymbol type)
    {
        var newer = patch.GetTypeByMetadataName(SymbolMetadataName(type));
        if (newer == null)
            return Array.Empty<ISymbol>();
        var names = Members(type).Select(m => m.Name).ToHashSet();
        return Members(newer).Where(Mutable).Where(m => !names.Contains(m.Name)).ToArray();
    }

    private string PatchParameters(INamedTypeSymbol type, HashSet<string> excluded)
    {
        var parameters = MemberParameters(PatchMembers(type), excluded);
        return parameters.Count == 0
            ? ""
            : "\n#if PINE_UNITY_6000_3_25_OR_NEWER\n,"
                + string.Join(",\n", parameters)
                + "\n#endif\n";
    }

    private void ApplyPatch(INamedTypeSymbol type, HashSet<string> excluded, StringBuilder output)
    {
        var members = PatchMembers(type);
        if (members.Length == 0)
            return;
        output.AppendLine("#if PINE_UNITY_6000_3_25_OR_NEWER");
        SetMembers(output, members, excluded);
        output.AppendLine("#endif");
    }

    private static IEnumerable<INamedTypeSymbol> Bases(INamedTypeSymbol type)
    {
        for (var t = type; t != null; t = t.BaseType)
            yield return t;
    }

    private static string MetadataName(JsonElement item)
    {
        var name = item.GetProperty("type").GetString()!;
        var generic = name.IndexOf('<');
        name = name.Replace("GraphView.Layer", "GraphView+Layer");
        return generic < 0
            ? name
            : name[..generic] + "`" + item.GetProperty("constraints").GetArrayLength();
    }

    private static string MethodName(JsonElement item)
    {
        var type = item.GetProperty("type").GetString()!;
        var result = item.GetProperty("metadataName").GetString()!.Split('`')[0];
        if (type == "UnityEditor.Search.ObjectField")
            return "SearchObjectField";
        if (type == "UnityEditor.Experimental.GraphView.GraphView.Layer")
            return "GraphViewLayer";
        return result;
    }

    private static string Header =>
        "// <auto-generated/>\nusing System;\nusing System.Collections.Generic;\nusing Pine;\nusing Core = Pine.Core;\nnamespace Pine.UIToolkit\n{\n";

    private static IEnumerable<ISymbol> Members(INamedTypeSymbol type) =>
        Bases(type)
            .SelectMany(t => t.GetMembers())
            .Where(m => m.DeclaredAccessibility == Accessibility.Public && !m.IsStatic)
            .GroupBy(m => m.Name)
            .Select(g => g.First());

    private static bool Mutable(ISymbol member) =>
        !Obsolete(member)
        && member switch
        {
            IPropertySymbol p => !p.IsIndexer
                && p.SetMethod?.DeclaredAccessibility == Accessibility.Public
                && !Obsolete(p.SetMethod),
            IFieldSymbol f => !f.IsReadOnly && !f.IsConst,
            _ => false,
        };

    private static ITypeSymbol MemberType(ISymbol member) =>
        member switch
        {
            IPropertySymbol p => p.Type,
            IFieldSymbol f => f.Type,
            IEventSymbol e => e.Type,
            _ => throw new InvalidOperationException(),
        };

    private static string Generic(INamedTypeSymbol type) =>
        type.TypeParameters.Length == 0
            ? ""
            : "<" + string.Join(",", type.TypeParameters.Select(p => p.Name)) + ">";

    private static string Constraints(IEnumerable<ITypeParameterSymbol> parameters) =>
        string.Join(
            " ",
            parameters.Select(p =>
            {
                var list = new List<string>();
                if (p.HasReferenceTypeConstraint)
                    list.Add("class");
                if (p.HasValueTypeConstraint)
                    list.Add("struct");
                list.AddRange(p.ConstraintTypes.Select(Type));
                if (p.HasConstructorConstraint && !p.HasValueTypeConstraint)
                    list.Add("new()");
                return list.Count == 0 ? "" : "where " + p.Name + ":" + string.Join(",", list);
            })
        );

    private static bool ConvertedValue(ITypeSymbol type) =>
        type is INamedTypeSymbol named
        && type.TypeKind == TypeKind.Struct
        && !named.IsRefLikeType
        && type.SpecialType == SpecialType.None
        && (
            named.ToDisplayString() == "Unity.Properties.PropertyPath"
            || named
                .GetMembers("op_Implicit")
                .OfType<IMethodSymbol>()
                .Any(m => SymbolEqualityComparer.Default.Equals(m.ReturnType, type))
        );

    private static string NullableValue(ITypeSymbol type) =>
        ConvertedValue(type)
            ? Adapter((INamedTypeSymbol)type) + "?"
            : "global::Pine.Value<" + Type(type) + ">?";

    private static string ValueArgument(ITypeSymbol type, string name) =>
        ConvertedValue(type)
            ? name
                + ".HasValue ? (global::Pine.Value<"
                + Type(type)
                + ">?)"
                + name
                + ".Value.Value : null"
            : name;

    private static string OnName(string eventName) =>
        eventName.StartsWith("On", StringComparison.Ordinal) && eventName.Length > 2
            ? "on" + eventName[2..]
            : "on" + char.ToUpperInvariant(eventName[0]) + eventName[1..];

    private static string Callback(ITypeSymbol callbackType, string callback, string node)
    {
        var invoke = ((INamedTypeSymbol)callbackType).DelegateInvokeMethod!;
        var args = invoke.Parameters.Select((p, i) => "@argument" + i).ToArray();
        var byRef = invoke.Parameters.Any(p => p.RefKind != RefKind.None);
        var declarations = invoke.Parameters.Select(
            (p, i) =>
                !byRef
                    ? args[i]
                    : (
                        p.RefKind == RefKind.None
                            ? ""
                            : p.RefKind.ToString().ToLowerInvariant() + " "
                    )
                        + Type(p.Type)
                        + " "
                        + args[i]
        );
        var arguments = invoke.Parameters.Select(
            (p, i) =>
                (p.RefKind == RefKind.None ? "" : p.RefKind.ToString().ToLowerInvariant() + " ")
                + (p.RefKind == RefKind.None ? args[i] : "local" + i)
        );
        var call =
            "Scoped(" + node + ", () => " + callback + "(" + string.Join(",", arguments) + "))";
        if (!byRef)
            return "("
                + Type(callbackType)
                + ")(("
                + string.Join(",", declarations)
                + ") => "
                + call
                + ")";
        var locals = invoke
            .Parameters.Select((p, i) => (p, i))
            .Where(x => x.p.RefKind != RefKind.None)
            .Select(x =>
                Type(x.p.Type)
                + " local"
                + x.i
                + " = "
                + (x.p.RefKind == RefKind.Out ? "default(" + Type(x.p.Type) + ")" : args[x.i])
                + ";"
            );
        var assign = invoke
            .Parameters.Select((p, i) => (p, i))
            .Where(x => x.p.RefKind is RefKind.Ref or RefKind.Out)
            .Select(x => args[x.i] + " = local" + x.i + ";");
        return "("
            + Type(callbackType)
            + ")(("
            + string.Join(",", declarations)
            + ") => { "
            + string.Join(" ", locals)
            + " try { "
            + (invoke.ReturnsVoid ? "" : "return ")
            + call
            + "; } finally { "
            + string.Join(" ", assign)
            + " } })";
    }

    private static List<string> Common(INamedTypeSymbol type, bool dynamic) =>
        new()
        {
            dynamic ? "Func<IEnumerable<View>> children" : "View[] children = null",
            "Value<Style>? style = null",
            "Value<string[]>? classes = null",
            "Value<global::UnityEngine.UIElements.StyleSheet[]>? styleSheets = null",
            "Event[] events = null",
            "Binding[] bindings = null",
            "Target[] targets = null",
            "global::UnityEngine.UIElements.IManipulator[] manipulators = null",
            "Action<" + Type(type) + "> reference = null",
            "Action<" + Type(type) + "> configure = null",
            "Value<bool>? enabled = null",
        };

    private static string CommonCall(bool dynamic) =>
        "children: "
        + (dynamic ? "null" : "children")
        + ", readChildren: "
        + (dynamic ? "children" : "null")
        + ", style: style, classes: classes, styleSheets: styleSheets, events: events, bindings: bindings, targets: targets, manipulators: manipulators, reference: reference, configure: configure, enabled: enabled";

    private static List<string> MemberParameters(
        IEnumerable<ISymbol> members,
        HashSet<string> excluded
    )
    {
        var output = new List<string>();
        foreach (
            var member in members
                .Where(Mutable)
                .Where(m => !excluded.Contains(m.Name))
                .OrderBy(m =>
                    m.Name == "text" ? 0
                    : m.Name == "value" ? 1
                    : m.Name == "label" ? 2
                    : 3
                )
                .ThenBy(m => m.Name)
        )
        {
            var native = MemberType(member);
            if (native.TypeKind == TypeKind.Delegate)
            {
                output.Add(Type(native) + " @" + member.Name + " = null");
                output.Add(NullableValue(native) + " @" + member.Name + "Value = null");
            }
            else
                output.Add(NullableValue(native) + " @" + member.Name + " = null");
        }
        foreach (var ev in members.OfType<IEventSymbol>().Where(e => !Obsolete(e)))
            output.Add(Type(ev.Type) + " @" + OnName(ev.Name) + " = null");
        return output;
    }

    private static void SetMembers(
        StringBuilder output,
        IEnumerable<ISymbol> members,
        HashSet<string> excluded,
        string target = "native",
        string node = "node"
    )
    {
        foreach (var member in members.Where(Mutable).Where(m => !excluded.Contains(m.Name)))
        {
            var native = MemberType(member);
            var name = member.Name;
            if (native.TypeKind == TypeKind.Delegate)
            {
                output.AppendLine(
                    "if (@"
                        + name
                        + " != null) CallbackProp<"
                        + Type(member.ContainingType)
                        + ","
                        + Type(native)
                        + ">("
                        + target
                        + ", "
                        + node
                        + ", \""
                        + name
                        + "\", new Value<"
                        + Type(native)
                        + ">("
                        + Callback(native, "@" + name, node)
                        + "), item => item.@"
                        + name
                        + ", (item,v) => item.@"
                        + name
                        + " = v);"
                );
                output.AppendLine(
                    "CallbackProp("
                        + target
                        + ", "
                        + node
                        + ", \""
                        + name
                        + "\", @"
                        + name
                        + "Value, item => item.@"
                        + name
                        + ", (item,v) => item.@"
                        + name
                        + " = v == null ? null : "
                        + Callback(native, "v", node)
                        + ");"
                );
            }
            else
                output.AppendLine(
                    "Prop("
                        + target
                        + ", "
                        + node
                        + ", \""
                        + name
                        + "\", "
                        + ValueArgument(native, "@" + name)
                        + ", (item,v) => item.@"
                        + name
                        + " = v);"
                );
        }
        foreach (var ev in members.OfType<IEventSymbol>().Where(e => !Obsolete(e)))
        {
            var parameter = "@" + OnName(ev.Name);
            output.AppendLine(
                "if ("
                    + parameter
                    + " != null) Listen("
                    + node
                    + ", "
                    + Callback(ev.Type, parameter, node)
                    + ", handler => "
                    + target
                    + ".@"
                    + ev.Name
                    + " += handler, handler => "
                    + target
                    + ".@"
                    + ev.Name
                    + " -= handler);"
            );
        }
    }

    public string Factories()
    {
        factory.Append(Header).AppendLine("public static partial class P {");
        foreach (var item in baselineJson.GetProperty("controls").EnumerateArray())
        {
            var type = baseline.GetTypeByMetadataName(MetadataName(item));
            if (type == null)
                throw new InvalidOperationException("Missing type " + item.GetProperty("type"));
            var editor =
                type.ContainingAssembly.Name.StartsWith("UnityEditor", StringComparison.Ordinal)
                || type.Name == "IMGUIContainer";
            if (editor)
                factory.AppendLine("#if UNITY_EDITOR");
            var ctors = type
                .InstanceConstructors.Where(c =>
                    c.DeclaredAccessibility == Accessibility.Public && !Obsolete(c)
                )
                .ToArray();
            if (type.IsAbstract)
                EmitFactory(item, type, null, false, true);
            else if (type.ToDisplayString() == "UnityEditor.Experimental.GraphView.Port")
                EmitPort(item, type);
            else
                foreach (var ctor in ctors)
                {
                    EmitFactory(item, type, ctor, false, false);
                    EmitFactory(item, type, ctor, true, false);
                }
            if (type.IsAbstract)
                EmitFactory(item, type, null, true, true);
            if (editor)
                factory.AppendLine("#endif");
        }
        factory.AppendLine("}\n}");
        return factory.ToString();
    }

    private void EmitFactory(
        JsonElement item,
        INamedTypeSymbol type,
        IMethodSymbol? ctor,
        bool dynamic,
        bool abstractFactory
    )
    {
        var nativeType = Type(type);
        var all = Members(type).ToArray();
        var excluded = new HashSet<string>(Common(type, false).Select(p => p.Split(' ')[1]));
        excluded.UnionWith(
            new[]
            {
                "children",
                "style",
                "classes",
                "styleSheets",
                "events",
                "bindings",
                "targets",
                "reference",
                "configure",
                "enabled",
            }
        );
        var parameters = new List<string>();
        if (abstractFactory)
            parameters.Add("Func<" + nativeType + "> create");
        else
            foreach (var param in ctor!.Parameters)
            {
                parameters.Add(
                    Type(param.Type)
                        + " @"
                        + (param.Name == "columns" ? "nativeColumns" : param.Name)
                );
                excluded.Add(param.Name);
            }
        var input = type.AllInterfaces.FirstOrDefault(i =>
            i.OriginalDefinition.ToDisplayString()
            == "UnityEngine.UIElements.INotifyValueChanged<T>"
        );
        if (input != null && !excluded.Contains("value"))
        {
            excluded.Add("value");
            parameters.Add(NullableValue(input.TypeArguments[0]) + " value = null");
            parameters.Add("Action<" + Type(input.TypeArguments[0]) + "> onValueChanged = null");
        }
        else if (input != null)
            parameters.Add("Action<" + Type(input.TypeArguments[0]) + "> onValueChanged = null");
        var memberParameters = MemberParameters(all, excluded);
        var extra = new List<string>();
        if (type.Name is "MultiColumnListView" or "MultiColumnTreeView")
            extra.AddRange(
                new[]
                {
                    "global::UnityEngine.UIElements.Column[] columns = null",
                    "global::UnityEngine.UIElements.SortColumnDescription[] sortColumnDescriptions = null",
                }
            );
        if (Bases(type).Any(t => t.Name == "BaseVerticalCollectionView"))
            extra.Add("Rows rows = null");
        if (type.Name == "RepeatButton" && ctor?.Parameters.Length == 0)
            extra.AddRange(
                new[]
                {
                    "Action onClick = null",
                    "Value<long>? delay = null",
                    "Value<long>? interval = null",
                }
            );
        if (type.Name is "EnumField" or "EnumFlagsField" && ctor?.Parameters.Length == 0)
            extra.Add("Value<bool>? includeObsoleteValues = null");
        AddInterfaceParameters(all, memberParameters);
        var common = Common(type, dynamic);
        if (dynamic)
            parameters.Insert(abstractFactory ? 1 : ctor?.Parameters.Length ?? 0, common[0]);
        else
            memberParameters.Add(common[0]);
        parameters.AddRange(memberParameters);
        parameters.AddRange(extra);
        parameters.AddRange(common.Skip(1));
        // Required constructor inputs precede every optional input, including the reactive-children overload.
        factory.AppendLine(
            "public static View "
                + MethodName(item)
                + Generic(type)
                + "("
                + string.Join(",\n", parameters)
                + PatchParameters(type, excluded)
                + ") "
                + Constraints(type.TypeParameters)
                + " {"
        );
        var ctorHasDelegate =
            ctor?.Parameters.Any(p => p.Type.TypeKind == TypeKind.Delegate) == true;
        string creation;
        if (abstractFactory)
            creation = "create";
        else
        {
            var args = ctor!.Parameters.Select(p =>
                p.Type.TypeKind == TypeKind.Delegate
                    ? "(@"
                        + p.Name
                        + " == null ? null : "
                        + Callback(p.Type, "@" + p.Name, "constructorNode")
                        + ")"
                    : "@" + (p.Name == "columns" ? "nativeColumns" : p.Name)
            );
            creation = ctorHasDelegate
                ? "() => { var constructorNode = new Node(null, Core.RequireScope()); return new "
                    + nativeType
                    + "("
                    + string.Join(",", args)
                    + "); }"
                : "() => new " + nativeType + "(" + string.Join(",", args) + ")";
        }
        if (type.Name == "EnumField" && ctor?.Parameters.Length == 0)
            creation = "() => new global::UnityEngine.UIElements.EnumField(ReadInitial(value))";
        if (type.Name == "EnumFlagsField" && ctor?.Parameters.Length == 0)
            creation =
                "() => new global::UnityEditor.UIElements.EnumFlagsField(null, ReadInitial(value), ReadInitial(includeObsoleteValues))";
        factory.AppendLine("return BuildView(" + creation + ", (native,node) => {");
        if (ctor != null)
        {
            if (
                ctor.Parameters.Any(p =>
                    p.Name != "value" && !all.Any(m => m.Name == p.Name && Mutable(m))
                )
            )
                factory.AppendLine(
                    "if (node.IsExisting) throw new InvalidOperationException(\"Constructor-only inputs cannot apply to existing UXML targets. Use property inputs or configure.\");"
                );
            foreach (
                var parameter in ctor.Parameters.Where(p =>
                    p.Name != "value" && all.Any(m => m.Name == p.Name && Mutable(m))
                )
            )
            {
                factory.AppendLine("node.ClaimValue(\"" + parameter.Name + "\");");
                if (parameter.Type.TypeKind == TypeKind.Delegate)
                    factory.AppendLine(
                        "if (node.IsExisting) throw new InvalidOperationException(\"Constructor delegate inputs require a new native control. Use the corresponding callback property.\");"
                    );
                else
                    factory.AppendLine(
                        "if (node.IsExisting) native.@"
                            + parameter.Name
                            + " = @"
                            + parameter.Name
                            + ";"
                    );
            }
        }
        if (type.Name == "EnumField" && ctor?.Parameters.Length == 0)
            factory.AppendLine(
                "if (ReadInitial(value) != null) native.Init(ReadInitial(value), ReadInitial(includeObsoleteValues));"
            );
        if (type.Name is "EnumField" or "EnumFlagsField" && ctor?.Parameters.Length == 0)
            factory.AppendLine(
                "Prop(native,node,\"includeObsoleteValues\",includeObsoleteValues,(item,v) => { var initial = ReadInitial(value); if (initial != null) item.Init(initial,v); });"
            );
        if (input != null)
        {
            var valueArg = ctor?.Parameters.FirstOrDefault(p => p.Name == "value");
            var value =
                valueArg == null
                    ? ValueArgument(input.TypeArguments[0], "value")
                    : "(Value<"
                        + Type(input.TypeArguments[0])
                        + ">?)new Value<"
                        + Type(input.TypeArguments[0])
                        + ">(@value)";
            factory.AppendLine(
                "InputProp<"
                    + Type(input.TypeArguments[0])
                    + ">(native,node,"
                    + value
                    + ",onValueChanged);"
            );
        }
        SetMembers(factory, all, excluded);
        ApplyPatch(type, excluded, factory);
        ApplyInterfaceArguments(all, factory);
        if (type.Name is "MultiColumnListView" or "MultiColumnTreeView")
            factory.AppendLine(
                "Columns(node,native.columns,columns); SortColumns(node,native.sortColumnDescriptions,sortColumnDescriptions);"
            );
        if (Bases(type).Any(t => t.Name == "BaseVerticalCollectionView"))
            factory.AppendLine("rows?.Apply(node,native);");
        if (type.Name == "RepeatButton" && ctor?.Parameters.Length == 0)
        {
            factory.AppendLine(
                "Action repeatAction = onClick == null ? null : (Action)(() => Scoped(node,onClick)); native.SetAction(repeatAction,ReadInitial(delay),ReadInitial(interval));"
            );
            factory.AppendLine(
                "Prop(native,node,\"delay\",delay,(item,v) => item.SetAction(repeatAction,v,ReadInitial(interval))); Prop(native,node,\"interval\",interval,(item,v) => item.SetAction(repeatAction,ReadInitial(delay),v));"
            );
        }
        factory.AppendLine("}, " + CommonCall(dynamic) + ");\n}");
        FactoryCount++;
    }

    private static void AddInterfaceParameters(
        IEnumerable<ISymbol> members,
        List<string> parameters
    )
    {
        foreach (
            var member in members
                .OfType<IPropertySymbol>()
                .Where(p =>
                    !Obsolete(p)
                    && p.GetMethod?.DeclaredAccessibility == Accessibility.Public
                    && p.Type.ToDisplayString()
                        is "UnityEngine.UIElements.ITextEdition"
                            or "UnityEngine.UIElements.ITextSelection"
                )
        )
            parameters.Add("Action<" + Type(member.Type) + "> @" + member.Name + " = null");
    }

    private static void ApplyInterfaceArguments(IEnumerable<ISymbol> members, StringBuilder output)
    {
        foreach (
            var member in members
                .OfType<IPropertySymbol>()
                .Where(p =>
                    !Obsolete(p)
                    && p.GetMethod?.DeclaredAccessibility == Accessibility.Public
                    && p.Type.ToDisplayString()
                        is "UnityEngine.UIElements.ITextEdition"
                            or "UnityEngine.UIElements.ITextSelection"
                )
        )
            output.AppendLine(
                "if (@"
                    + member.Name
                    + " != null) @"
                    + member.Name
                    + "(native.@"
                    + member.Name
                    + ");"
            );
    }

    private void EmitPort(JsonElement item, INamedTypeSymbol type)
    {
        var create = type.GetMembers("Create")
            .OfType<IMethodSymbol>()
            .Single(m => m.IsStatic && m.DeclaredAccessibility == Accessibility.Public);
        foreach (var dynamic in new[] { false, true })
        {
            var excluded = new HashSet<string>(create.Parameters.Select(p => p.Name));
            var members = Members(type).ToArray();
            var parameters = create.Parameters.Select(p => Type(p.Type) + " @" + p.Name).ToList();
            var common = Common(type, dynamic);
            if (dynamic)
                parameters.Add(common[0]);
            parameters.AddRange(MemberParameters(members, excluded));
            if (!dynamic)
                parameters.Add(common[0]);
            parameters.AddRange(common.Skip(1));
            factory.AppendLine(
                "public static View Port<TEdge>("
                    + string.Join(",\n", parameters)
                    + ") "
                    + Constraints(create.TypeParameters)
                    + " { return BuildView(() => global::UnityEditor.Experimental.GraphView.Port.Create<TEdge>("
                    + string.Join(",", create.Parameters.Select(p => "@" + p.Name))
                    + "), (native,node) => {"
            );
            SetMembers(factory, members, excluded);
            factory.AppendLine("}," + CommonCall(dynamic) + "); }");
            FactoryCount++;
        }
    }

    public string Styles()
    {
        var output = new StringBuilder(Header);
        var style = baseline.GetTypeByMetadataName("UnityEngine.UIElements.IStyle")!;
        var properties = style
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => Mutable(p))
            .ToArray();
        StyleCount = properties.Length;
        var converted = baselineJson
            .GetProperty("controls")
            .EnumerateArray()
            .Concat(baselineJson.GetProperty("infrastructure").EnumerateArray())
            .Concat(baselineJson.GetProperty("auxiliary").EnumerateArray())
            .Select(item => baseline.GetTypeByMetadataName(MetadataName(item)))
            .Where(t => t != null)
            .SelectMany(t => Members(t!))
            .Where(Mutable)
            .Select(MemberType)
            .Where(ConvertedValue)
            .Cast<INamedTypeSymbol>();
        foreach (
            var native in properties
                .Select(p => (INamedTypeSymbol)p.Type)
                .Concat(converted)
                .Select(t => t.OriginalDefinition)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
        )
            EmitAdapter(output, native);
        output.AppendLine("public sealed partial class Style {");
        foreach (var property in properties)
            output.AppendLine(
                "public " + Adapter((INamedTypeSymbol)property.Type) + "? @" + property.Name + ";"
            );
        output.AppendLine(
            "internal void Apply(Node node,global::UnityEngine.UIElements.VisualElement target) {"
        );
        foreach (var property in properties)
            output.AppendLine(
                "P.Prop(target,node,\"style."
                    + property.Name
                    + "\", @"
                    + property.Name
                    + ".HasValue ? (Value<"
                    + Type(property.Type)
                    + ">?)@"
                    + property.Name
                    + ".Value.Value : null, (item,v) => item.style.@"
                    + property.Name
                    + " = v);"
            );
        output.AppendLine("}\n}\n}");
        return output.ToString();
    }

    private static string Adapter(INamedTypeSymbol native) =>
        native.Name
        + "Value"
        + (
            native.TypeArguments.Length == 0
                ? ""
                : "<" + string.Join(",", native.TypeArguments.Select(Type)) + ">"
        );

    private static void EmitAdapter(StringBuilder output, INamedTypeSymbol native)
    {
        var adapter = Adapter(native);
        var nativeType = Type(native);
        output.AppendLine(
            "public readonly struct " + adapter + " " + Constraints(native.TypeParameters) + " {"
        );
        output.AppendLine(
            "internal readonly Value<"
                + nativeType
                + "> Value; internal "
                + native.Name
                + "Value(Value<"
                + nativeType
                + "> value) { Value = value; }"
        );
        var inputs = native
            .GetMembers("op_Implicit")
            .OfType<IMethodSymbol>()
            .Where(m => SymbolEqualityComparer.Default.Equals(m.ReturnType, native))
            .Select(m => m.Parameters[0].Type)
            .Prepend(native)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<ITypeSymbol>()
            .ToList();
        foreach (var input in inputs.Distinct(SymbolEqualityComparer.Default).Cast<ITypeSymbol>())
            EmitAdapterInput(output, native, adapter, input);
        if (native.ToDisplayString() == "Unity.Properties.PropertyPath")
            EmitAdapterInput(output, native, adapter, "string");
        if (
            inputs.Any(t => t.SpecialType == SpecialType.System_Single)
            && !inputs.Any(t => t.SpecialType == SpecialType.System_Int32)
        )
            EmitAdapterInput(output, native, adapter, "int");
        output.AppendLine("}");
    }

    private static void EmitAdapterInput(
        StringBuilder output,
        INamedTypeSymbol native,
        string adapter,
        ITypeSymbol input
    ) => EmitAdapterInput(output, native, adapter, Type(input));

    private static void EmitAdapterInput(
        StringBuilder output,
        INamedTypeSymbol native,
        string adapter,
        string input
    )
    {
        var nativeType = Type(native);
        var same = input == nativeType;
        string Convert(string expression) =>
            native.ToDisplayString() == "Unity.Properties.PropertyPath" && input == "string"
                ? "new " + nativeType + "(" + expression + ")"
                : "(" + nativeType + ")" + expression;
        output.AppendLine(
            "public static implicit operator "
                + adapter
                + "("
                + input
                + " value) => new "
                + adapter
                + "(new Value<"
                + nativeType
                + ">("
                + Convert("value")
                + "));"
        );
        output.AppendLine(
            "public static implicit operator "
                + adapter
                + "(Value<"
                + input
                + "> value) => new "
                + adapter
                + "("
                + (
                    same
                        ? "value"
                        : "new Value<" + nativeType + ">(() => " + Convert("value.Read()") + ")"
                )
                + ");"
        );
        foreach (var wrapper in new[] { "Source", "ReadOnly", "Derived", "Spring" })
            output.AppendLine(
                "public static implicit operator "
                    + adapter
                    + "("
                    + wrapper
                    + "<"
                    + input
                    + "> value) => value == null ? throw new ArgumentNullException(nameof(value)) : new "
                    + adapter
                    + "("
                    + (
                        same && wrapper == "Source"
                            ? "(Value<" + nativeType + ">)value"
                            : "new Value<" + nativeType + ">(() => " + Convert("value.Value") + ")"
                    )
                    + ");"
            );
    }

    public string Schemas()
    {
        var output = new StringBuilder(Header).AppendLine("public static partial class P {");
        foreach (
            var name in new[] { "ITextEdition", "ITextSelection", "PanelSettings", "UIDocument" }
        )
        {
            var type = baseline.GetTypeByMetadataName("UnityEngine.UIElements." + name)!;
            var members = Members(type)
                .Where(m => name != "UIDocument" || m.Name != "runInEditMode")
                .ToArray();
            var method = name.StartsWith("IText", StringComparison.Ordinal) ? name[1..] : name;
            string editorParameter =
                name == "UIDocument"
                    ? "\n#if UNITY_EDITOR\n,Value<bool>? runInEditMode = null\n#endif\n"
                    : "";
            output.AppendLine(
                "public static Action<"
                    + Type(type)
                    + "> "
                    + method
                    + "("
                    + string.Join(",\n", MemberParameters(members, new()))
                    + PatchParameters(type, new())
                    + editorParameter
                    + ") => native => { var node = global::Pine.UIToolkit.Node.Current ?? new Node(null,Core.RequireScope());"
            );
            SetMembers(output, members, new());
            ApplyPatch(type, new(), output);
            if (name == "UIDocument")
                output.AppendLine(
                    "#if UNITY_EDITOR\nProp(native,node,\"runInEditMode\",runInEditMode,(item,v)=>item.runInEditMode=v);\n#endif"
                );
            output.AppendLine("};");
        }
        foreach (
            var item in baselineJson
                .GetProperty("infrastructure")
                .EnumerateArray()
                .Concat(baselineJson.GetProperty("auxiliary").EnumerateArray())
        )
        {
            var type = baseline.GetTypeByMetadataName(MetadataName(item));
            if (
                type == null
                || type.IsAbstract
                || type.TypeKind != TypeKind.Class
                || type.InstanceConstructors.All(c =>
                    c.DeclaredAccessibility != Accessibility.Public || Obsolete(c)
                )
                || type.Name is "Painter2D" or "VisualTreeAsset"
            )
                continue;
            var editor = type.ContainingAssembly.Name.StartsWith(
                "UnityEditor",
                StringComparison.Ordinal
            );
            if (editor)
                output.AppendLine("#if UNITY_EDITOR");
            foreach (
                var ctor in type.InstanceConstructors.Where(c =>
                    c.DeclaredAccessibility == Accessibility.Public && !Obsolete(c)
                )
            )
            {
                var members = Members(type).ToArray();
                var excluded = new HashSet<string>(ctor.Parameters.Select(p => p.Name));
                var parameters = ctor.Parameters.Select(p => Type(p.Type) + " @" + p.Name).ToList();
                parameters.AddRange(MemberParameters(members, excluded));
                if (type.Name == "Columns")
                    parameters.Add("global::UnityEngine.UIElements.Column[] items = null");
                if (type.Name == "SortColumnDescriptions")
                    parameters.Add(
                        "global::UnityEngine.UIElements.SortColumnDescription[] items = null"
                    );
                if (type.Name == "Column")
                    parameters.Add("Cell cell = null");
                output.AppendLine(
                    "public static "
                        + Type(type)
                        + " "
                        + MethodName(item)
                        + Generic(type)
                        + "("
                        + string.Join(",\n", parameters)
                        + ") "
                        + Constraints(type.TypeParameters)
                        + " { var node = new Node(null,Core.RequireScope()); var native = new "
                        + Type(type)
                        + "("
                        + string.Join(
                            ",",
                            ctor.Parameters.Select(p =>
                                p.Type.TypeKind == TypeKind.Delegate
                                    ? "(@"
                                        + p.Name
                                        + " == null ? null : "
                                        + Callback(p.Type, "@" + p.Name, "node")
                                        + ")"
                                    : "@" + p.Name
                            )
                        )
                        + ");"
                );
                SetMembers(output, members, excluded);
                if (type.Name == "Columns")
                    output.AppendLine("Columns(node,native,items);");
                if (type.Name == "SortColumnDescriptions")
                    output.AppendLine("SortColumns(node,native,items);");
                if (type.Name == "Column")
                    output.AppendLine("Cells(node,native,cell);");
                output.AppendLine("return native; }");
            }
            if (editor)
                output.AppendLine("#endif");
        }
        output.AppendLine("}\n}");
        return output.ToString();
    }
}
